// Code generated by MockGen. DO NOT EDIT.
// Source: compFacade.go

// Package compmocks is a generated GoMock package.
package compmocks

import (
	context "context"
	reflect "reflect"

	leaderboard "github.com/calebtracey/rugby-models/pkg/dtos/leaderboard"
	gomock "github.com/golang/mock/gomock"
)

// MockFacadeI is a mock of FacadeI interface.
type MockFacadeI struct {
	ctrl     *gomock.Controller
	recorder *MockFacadeIMockRecorder
}

// MockFacadeIMockRecorder is the mock recorder for MockFacadeI.
type MockFacadeIMockRecorder struct {
	mock *MockFacadeI
}

// NewMockFacadeI creates a new mock instance.
func NewMockFacadeI(ctrl *gomock.Controller) *MockFacadeI {
	mock := &MockFacadeI{ctrl: ctrl}
	mock.recorder = &MockFacadeIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacadeI) EXPECT() *MockFacadeIMockRecorder {
	return m.recorder
}

// CrawlAllLeaderboards mocks base method.
func (m *MockFacadeI) CrawlAllLeaderboards(ctx context.Context) leaderboard.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CrawlAllLeaderboards", ctx)
	ret0, _ := ret[0].(leaderboard.Response)
	return ret0
}

// CrawlAllLeaderboards indicates an expected call of CrawlAllLeaderboards.
func (mr *MockFacadeIMockRecorder) CrawlAllLeaderboards(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CrawlAllLeaderboards", reflect.TypeOf((*MockFacadeI)(nil).CrawlAllLeaderboards), ctx)
}

// CrawlLeaderboard mocks base method.
func (m *MockFacadeI) CrawlLeaderboard(ctx context.Context, req leaderboard.Request) leaderboard.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CrawlLeaderboard", ctx, req)
	ret0, _ := ret[0].(leaderboard.Response)
	return ret0
}

// CrawlLeaderboard indicates an expected call of CrawlLeaderboard.
func (mr *MockFacadeIMockRecorder) CrawlLeaderboard(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CrawlLeaderboard", reflect.TypeOf((*MockFacadeI)(nil).CrawlLeaderboard), ctx, req)
}
