// Code generated by MockGen. DO NOT EDIT.
// Source: dao.go

// Package compmocks is a generated GoMock package.
package compmocks

import (
	reflect "reflect"

	dtos "github.com/calebtracey/rugby-models/pkg/dtos"
	gomock "github.com/golang/mock/gomock"
)

// MockDAOI is a mock of DAOI interface.
type MockDAOI struct {
	ctrl     *gomock.Controller
	recorder *MockDAOIMockRecorder
}

// MockDAOIMockRecorder is the mock recorder for MockDAOI.
type MockDAOIMockRecorder struct {
	mock *MockDAOI
}

// NewMockDAOI creates a new mock instance.
func NewMockDAOI(ctrl *gomock.Controller) *MockDAOI {
	mock := &MockDAOI{ctrl: ctrl}
	mock.recorder = &MockDAOIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDAOI) EXPECT() *MockDAOIMockRecorder {
	return m.recorder
}

// CrawlLeaderboardData mocks base method.
func (m *MockDAOI) CrawlLeaderboardData(url string) (dtos.CompetitionLeaderboardData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CrawlLeaderboardData", url)
	ret0, _ := ret[0].(dtos.CompetitionLeaderboardData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CrawlLeaderboardData indicates an expected call of CrawlLeaderboardData.
func (mr *MockDAOIMockRecorder) CrawlLeaderboardData(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CrawlLeaderboardData", reflect.TypeOf((*MockDAOI)(nil).CrawlLeaderboardData), url)
}
