// Package openapi3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.0 DO NOT EDIT.
package openapi3

// CompetitionLeaderboardData defines model for CompetitionLeaderboardData.
type CompetitionLeaderboardData struct {
	CompId   *string                  `json:"compId"`
	CompName *string                  `json:"compName"`
	Teams    *TeamLeaderboardDataList `json:"teams,omitempty"`
}

// CompetitionLeaderboardDataList defines model for CompetitionLeaderboardDataList.
type CompetitionLeaderboardDataList = []CompetitionLeaderboardData

// ErrorLog defines model for ErrorLog.
type ErrorLog struct {
	Query     *string `json:"query"`
	RootCause *string `json:"rootCause"`
	Scope     *string `json:"scope"`
	Status    *string `json:"status"`
	Trace     *string `json:"trace"`
}

// ErrorLogs defines model for ErrorLogs.
type ErrorLogs = []ErrorLog

// Message defines model for Message.
type Message struct {
	Count     *string    `json:"count"`
	ErrorLog  *ErrorLogs `json:"errorLog,omitempty"`
	HostName  *string    `json:"hostName"`
	Status    *string    `json:"status"`
	TimeTaken *string    `json:"timeTaken"`
}

// TeamCompetitionStats defines model for TeamCompetitionStats.
type TeamCompetitionStats struct {
	BonusPoints       *string `json:"bonusPoints"`
	BonusPointsLosing *string `json:"bonusPointsLosing"`
	BonusPointsTry    *string `json:"bonusPointsTry"`
	Bye               *string `json:"bye"`
	DrawCount         *string `json:"drawCount"`
	GamesPlayed       *string `json:"gamesPlayed"`
	LossCount         *string `json:"lossCount"`
	Points            *string `json:"points"`
	PointsAgainst     *string `json:"pointsAgainst"`
	PointsDiff        *string `json:"pointsDiff"`
	PointsFor         *string `json:"pointsFor"`
	TriesAgainst      *string `json:"triesAgainst"`
	TriesFor          *string `json:"triesFor"`
	WinCount          *string `json:"winCount"`
}

// TeamLeaderboardData defines model for TeamLeaderboardData.
type TeamLeaderboardData struct {
	Abbr             *string               `json:"abbr"`
	CompetitionStats *TeamCompetitionStats `json:"competitionStats,omitempty"`
	Id               *string               `json:"id"`
	Name             *string               `json:"name"`
}

// TeamLeaderboardDataList defines model for TeamLeaderboardDataList.
type TeamLeaderboardDataList = []TeamLeaderboardData

// AllLeaderboardsResponse defines model for AllLeaderboardsResponse.
type AllLeaderboardsResponse struct {
	LeaderboardDataList *CompetitionLeaderboardDataList `json:"leaderboardDataList,omitempty"`
	Message             *Message                        `json:"message,omitempty"`
}

// LeaderboardResponse defines model for LeaderboardResponse.
type LeaderboardResponse struct {
	LeaderboardData *CompetitionLeaderboardData `json:"leaderboardData,omitempty"`
	Message         *Message                    `json:"message,omitempty"`
}

// LeaderboardRequest defines model for LeaderboardRequest.
type LeaderboardRequest struct {
	CompId   *string `json:"compId,omitempty"`
	CompName *string `json:"compName,omitempty"`
	Date     *string `json:"date,omitempty"`
	Source   *string `json:"source,omitempty"`
}

// GetLeaderboardDataJSONBody defines parameters for GetLeaderboardData.
type GetLeaderboardDataJSONBody struct {
	CompId   *string `json:"compId,omitempty"`
	CompName *string `json:"compName,omitempty"`
	Date     *string `json:"date,omitempty"`
	Source   *string `json:"source,omitempty"`
}

// GetLeaderboardDataJSONRequestBody defines body for GetLeaderboardData for application/json ContentType.
type GetLeaderboardDataJSONRequestBody GetLeaderboardDataJSONBody
