// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/calebtracey/rugby-crawler-api/internal/dao/comp (interfaces: MapperI)

// Package comp is a generated GoMock package.
package comp

import (
	reflect "reflect"

	models "github.com/calebtracey/rugby-crawler-api/external/models"
	gomock "github.com/golang/mock/gomock"
)

// MockMapperI is a mock of MapperI interface.
type MockMapperI struct {
	ctrl     *gomock.Controller
	recorder *MockMapperIMockRecorder
}

// MockMapperIMockRecorder is the mock recorder for MockMapperI.
type MockMapperIMockRecorder struct {
	mock *MockMapperI
}

// NewMockMapperI creates a new mock instance.
func NewMockMapperI(ctrl *gomock.Controller) *MockMapperI {
	mock := &MockMapperI{ctrl: ctrl}
	mock.recorder = &MockMapperIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapperI) EXPECT() *MockMapperIMockRecorder {
	return m.recorder
}

// BuildCrawlerUrl mocks base method.
func (m *MockMapperI) BuildCrawlerUrl(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildCrawlerUrl", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildCrawlerUrl indicates an expected call of BuildCrawlerUrl.
func (mr *MockMapperIMockRecorder) BuildCrawlerUrl(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildCrawlerUrl", reflect.TypeOf((*MockMapperI)(nil).BuildCrawlerUrl), arg0)
}

// CreateInsertLeaderboardExec mocks base method.
func (m *MockMapperI) CreateInsertLeaderboardExec(arg0, arg1 string, arg2 models.TeamLeaderboardData) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInsertLeaderboardExec", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	return ret0
}

// CreateInsertLeaderboardExec indicates an expected call of CreateInsertLeaderboardExec.
func (mr *MockMapperIMockRecorder) CreateInsertLeaderboardExec(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInsertLeaderboardExec", reflect.TypeOf((*MockMapperI)(nil).CreateInsertLeaderboardExec), arg0, arg1, arg2)
}

// CreateUpdateLeaderboardExec mocks base method.
func (m *MockMapperI) CreateUpdateLeaderboardExec(arg0, arg1 string, arg2 models.TeamLeaderboardData) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUpdateLeaderboardExec", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	return ret0
}

// CreateUpdateLeaderboardExec indicates an expected call of CreateUpdateLeaderboardExec.
func (mr *MockMapperIMockRecorder) CreateUpdateLeaderboardExec(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUpdateLeaderboardExec", reflect.TypeOf((*MockMapperI)(nil).CreateUpdateLeaderboardExec), arg0, arg1, arg2)
}

// MapAddPSQLCompetitionData mocks base method.
func (m *MockMapperI) MapAddPSQLCompetitionData(arg0, arg1 string, arg2 []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapAddPSQLCompetitionData", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	return ret0
}

// MapAddPSQLCompetitionData indicates an expected call of MapAddPSQLCompetitionData.
func (mr *MockMapperIMockRecorder) MapAddPSQLCompetitionData(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapAddPSQLCompetitionData", reflect.TypeOf((*MockMapperI)(nil).MapAddPSQLCompetitionData), arg0, arg1, arg2)
}
