Env: "Dev"
Port: 6080
AppName: "rugby-data-api"
ComponentConfigs:
  Client:
    Timeout: 15
    IdleConnTimeout: 15
    MaxIdleConsPerHost: 50
    MaxConsPerHost: 0
    DisableCompression: 2
    InsecureSkipVerify: 1
Databases:
  - Name: "PSQL"
    Database: "postgres"
    Server: "db.qcgjaptyxgcmagtvntln.supabase.co:5432"
    Username: "postgres"
    Scheme: "postgres"
    PasswordEnvVariable: "DB_PASSWORD_DEV"
Crawlers:
  - Name: "COLLY"
    AppsJSONPath: ""
    TimeoutSeconds: 3
    LoadingTimeoutSeconds: 3
    JSON: true
    MaxDepth: 2
    visitedLinks: 0
    MaxVisitedLinks: 100
    MsDelayBetweenRequests: 10
