Env: "Local"
Port: 6080
AppName: "rugby-data-api"
ComponentConfigs:
  Client:
    Timeout: 15
    IdleConnTimeout: 15
    MaxIdleConsPerHost: 50
    MaxConsPerHost: 0
    DisableCompression: 2
    InsecureSkipVerify: 1
Databases:
  - Name: "PSQL"
    Database: "rugby_db"
    Server: "localhost:5432"
    Username: "calebtracey"
    Scheme: "postgres"
    PasswordEnvVariable: "DB_PASSWORD_LOCAL"
Crawlers:
  - Name: "COLLY"
    AppsJSONPath: ""
    TimeoutSeconds: 3
    LoadingTimeoutSeconds: 3
    JSON: true
    MaxDepth: 2
    visitedLinks: 0
    MaxVisitedLinks: 100
    MsDelayBetweenRequests: 10
